# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codexlog < Formula
  desc "Browse, search, and analyze Codex CLI sessions"
  homepage "https://github.com/choplin/codexlog"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "2a19dd8f3af86128be5d45745dfb042ece1e1be497899b3ce7baa43119564611"

      def install
        bin.install "codexlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Darwin_arm64.tar.gz"
      sha256 "2ae5c1988d63a4ae67b8671826154dc168f61a132f99b45e751d1dd225d27510"

      def install
        bin.install "codexlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Linux_x86_64.tar.gz"
      sha256 "cc200ce7cb6f1fc208ab48381bc835e9678036301a36cd3ec35a436968ecc10d"
      def install
        bin.install "codexlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Linux_arm64.tar.gz"
      sha256 "2b00e752b42f2a95b7dc090fb0890b0c3b164436f99064887eb489344bb6efb2"
      def install
        bin.install "codexlog"
      end
    end
  end

  test do
    system "#{bin}/codexlog", "--version"
  end
end
