# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vault < Formula
  desc "vault.md - A knowledge vault for AI-assisted development"
  homepage "https://github.com/choplin/vault.md"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choplin/vault.md/releases/download/v0.1.0/vault.md_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "7cd92289a9aed559cb8c610902159997e1ac8c074fe142faf00bd9eb5ab80b83"

      def install
        bin.install "vault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choplin/vault.md/releases/download/v0.1.0/vault.md_0.1.0_Darwin_arm64.tar.gz"
      sha256 "85c532ac9ccf42581cf51b195b683b1b86be909e1cb94a66f3108121f07c6cf5"

      def install
        bin.install "vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/vault.md/releases/download/v0.1.0/vault.md_0.1.0_Linux_x86_64.tar.gz"
      sha256 "492dc7f2f081bfde75dee0603d57cdb8da0f4dfeb8a9469f3a92cd2471983feb"
      def install
        bin.install "vault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/vault.md/releases/download/v0.1.0/vault.md_0.1.0_Linux_arm64.tar.gz"
      sha256 "14da904f6e6d883477921c4482ffb876e5c70d34bbcf9aa9c120733b29cae50f"
      def install
        bin.install "vault"
      end
    end
  end

  test do
    system "#{bin}/vault", "--version"
  end
end
