# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtm < Formula
  desc "Minimal git worktree management tool"
  homepage "https://github.com/choplin/wtm"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choplin/wtm/releases/download/v0.5.0/wtm_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "d855044624e5b1164ec7e23080b681b248141d1cfa5cf5d187e7e1926ddfd4c7"

      def install
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choplin/wtm/releases/download/v0.5.0/wtm_0.5.0_Darwin_arm64.tar.gz"
      sha256 "1c7ec749264a644c3ea865ca315591cde728eb24c6914d2b23744a4039e9238e"

      def install
        bin.install "wtm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/wtm/releases/download/v0.5.0/wtm_0.5.0_Linux_x86_64.tar.gz"
      sha256 "e7c949bae57fef48e20a776713e04fe013982993cf970b7c7d5dd2a726736e25"
      def install
        bin.install "wtm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/wtm/releases/download/v0.5.0/wtm_0.5.0_Linux_arm64.tar.gz"
      sha256 "21be5853f3ccd05f8aa16906d87b3d111e6cf3ba5a03648e727751928daecd14"
      def install
        bin.install "wtm"
      end
    end
  end

  test do
    system "#{bin}/wtm version"
  end
end
