# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codexlog < Formula
  desc "Browse, search, and analyze Codex CLI sessions"
  homepage "https://github.com/choplin/codexlog"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6fc80a42e1f3affc042efb73117a85a1b8474b0206e7491a3ea23344f810fd85"

      def install
        bin.install "codexlog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c7b40539c0683bb4d79774aec19608a5eed897f39d046e29814c24ef8f13f6e7"

      def install
        bin.install "codexlog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Linux_x86_64.tar.gz"
      sha256 "6801e2a556a95a61d5ca5485273de33d70bb05e913dd9130533a02d2991f99a7"
      def install
        bin.install "codexlog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/choplin/codexlog/releases/download/v0.1.0/codexlog_0.1.0_Linux_arm64.tar.gz"
      sha256 "74e161c866f79abbc0eb3ed0ddc61fe06ebc5ece3b39d611bd15cd7393d4d2c0"
      def install
        bin.install "codexlog"
      end
    end
  end

  test do
    system "#{bin}/codexlog", "--version"
  end
end
